version: '3.8'

services:
  app:
    build:
      target: build
    command: bun run dev
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"